services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
  kafka-connect-standalone-0:
    image: kafka-connect-standalone:latest
    ports:
      - 8083:8083
    env_file:
      - .env
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-qgzqg5x0at.servicebus.windows.net:9093
      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-qgzqg5x0at.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-qgzqg5x0at.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
  kafka-connect-standalone-1:
    image: kafka-connect-standalone:latest
    ports:
      - 18083:8083
    env_file:
      - .env
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-yydfqytd2n.servicebus.windows.net:9093
      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-yydfqytd2n.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-yydfqytd2n.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
  kafka-connect-standalone-2:
    image: kafka-connect-standalone:latest
    env_file:
      - .env
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-gu1kwzwhcr.servicebus.windows.net:9093
      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-gu1kwzwhcr.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://analyticsdata-jdbc-3fb81a8b-39d0-4a09-a-gu1kwzwhcr.servicebus.windows.net/;SharedAccessKeyName=jan26;SharedAccessKey=";
    ports:
      - 28083:8083